# Generated by Django 3.0.5 on 2023-03-29 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_ebookforclass_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('student_id', models.IntegerField()),
                ('Mark', models.CharField(max_length=50)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='attendees',
            name='roll_no',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
