# Generated by Django 4.0.1 on 2023-03-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_course_id_alter_details_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role_no',
            field=models.IntegerField(),
        ),
    ]
