# Generated by Django 3.0.5 on 2023-04-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20230402_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('notes_title', models.CharField(max_length=100)),
                ('regulation', models.CharField(max_length=100)),
                ('subcode', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='notes/')),
            ],
        ),
    ]
