# Generated by Django 3.0.5 on 2023-04-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_sec_daily_test_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('event_name', models.CharField(max_length=100)),
                ('event_photo', models.URLField()),
                ('event_description', models.TextField()),
                ('poster_link', models.URLField()),
            ],
        ),
    ]
