# Generated by Django 3.0.5 on 2023-04-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20230406_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Annauni_num',
            field=models.CharField(default='0000000', max_length=40),
        ),
    ]
