# Generated by Django 3.0.5 on 2023-04-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20230406_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cover_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjmopBq5-9ahdOGX8avTtihgiJ3VOkLGkAVV_2Fr_Xhg&usqp=CAU&ec=48665699', max_length=100),
            preserve_default=False,
        ),
    ]
