# Generated by Django 3.0.5 on 2023-04-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_auto_20230407_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internal_test_mark',
            name='user_name',
        ),
        migrations.AddField(
            model_name='internal_test_mark',
            name='assesment_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
