# Generated by Django 3.0.5 on 2023-04-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_auto_20230407_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(default='Author not provied any description', max_length=2000),
        ),
    ]
