# Generated by Django 3.0.5 on 2023-04-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_blog_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(default='Blog', max_length=2000),
        ),
    ]
