# Generated by Django 3.0.2 on 2023-04-19 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_auto_20230408_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookforclass',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
