# Generated by Django 3.0.2 on 2023-04-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_ebookforclass_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('html', models.TextField()),
                ('css', models.TextField()),
                ('preview_link', models.TextField()),
            ],
        ),
    ]
