# Generated by Django 4.0.1 on 2023-07-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_category_youtubelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_blog',
            name='reviewed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubelink',
            name='class_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
