# Generated by Django 4.0.1 on 2023-07-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_draft_blog_reviewed_youtubelink_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='class_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
