# Generated by Django 4.0.1 on 2023-07-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_category_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft_blog',
            name='Submitreview',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
