# Generated by Django 4.0.1 on 2023-07-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_draft_blog_submitreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reviewed_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
