# Generated by Django 4.0.1 on 2023-07-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='image',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
