# Generated by Django 4.0.1 on 2023-07-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_notifications_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='Reson',
            field=models.CharField(default='None...!', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='role_no',
            field=models.IntegerField(unique=True),
        ),
    ]
