# Generated by Django 4.0.1 on 2023-07-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_socialmedialinks_github_socialmedialinks_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_by', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='assignments/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
