# Generated by Django 4.0.1 on 2023-07-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='file',
        ),
    ]
