# Generated by Django 4.0.1 on 2023-07-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_remove_assignment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_by', models.IntegerField()),
                ('File', models.FileField(upload_to='upload_assignments/')),
                ('Assignment_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
