# Generated by Django 4.0.1 on 2023-07-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_upload_assignment_assignment_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='connect_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
