# Generated by Django 4.0.1 on 2023-07-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_users_connect_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_mark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('Assignment_id', models.IntegerField()),
                ('mark', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
