# Generated by Django 4.0.1 on 2023-07-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='user',
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='facebook',
            field=models.URLField(blank=True, default='Not Updated', null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='github',
            field=models.URLField(blank=True, default='Not Updated', null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.URLField(blank=True, default='Not Updated', null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='linkedin',
            field=models.URLField(blank=True, default='Not Updated', null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='portfolio',
            field=models.URLField(blank=True, default='Not Updated', null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='twitter',
            field=models.URLField(blank=True, default='Not Updated', null=True),
        ),
    ]
