# Generated by Django 4.0.1 on 2023-07-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_remove_socialmedia_user_alter_socialmedia_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_mail_id',
            field=models.CharField(default='sample@gmail.com', max_length=40),
        ),
    ]
