# Generated by Django 4.0.1 on 2023-07-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_student_parent_mail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mail_id',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_mail_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
