# Generated by Django 4.0.1 on 2023-07-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_botcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcontrol',
            name='usr_id',
            field=models.IntegerField(),
        ),
    ]
