# Generated by Django 4.0.1 on 2023-07-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_alter_botcontrol_usr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='class_type',
            field=models.CharField(default='subject', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty_details',
            name='qualififcation',
            field=models.CharField(default='qualification', max_length=200),
        ),
    ]
